# Generated by Django 4.2.5 on 2024-03-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="get_sugetion",
            fields=[
                ("request_id", models.AutoField(primary_key=True, serialize=False)),
                ("added_date", models.DateTimeField(auto_now=True)),
                ("f_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("phone", models.IntegerField()),
                ("subject", models.CharField(max_length=60)),
                ("about", models.TextField(max_length=150)),
            ],
        ),
    ]
