# Generated by Django 4.2.5 on 2024-03-15 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kit_apps", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="get_sugetion",
            new_name="StudentSuggestion",
        ),
    ]
