# Generated by Django 4.2.5 on 2024-04-04 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kit_apps", "0003_visitor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Visitor",
        ),
    ]
